name: github_api_app
description: A Flutter project that consumes the github api.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.3
  mocktail: ^0.2.0

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true